[package]
name = "rsrvr"
version = "0.2.5"
edition = "2021"
repository = "https://github.com/sector-f-labs/reservoir"
authors = ["Divan Visagie <me@divanv.com>"]
license = "BSD-3-Clause"
description = "Store all your Language Model Interactions"

[[bin]]
name = "reservoir"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"
anyhow = "1.0"
neo4rs = "0.8.0"
uuid = { version = "1.17.0", features = ["v4"] }
clap = { version = "4.5.39", features = ["derive"] }
once_cell = "1.21"
toml = "0.8.22"
dirs-next = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fastembed = "4.8.0"
async-trait = "0.1"
