services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*,vectorization.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*,vectorization.*"
      # Updated memory settings with new names and reduced values
      NEO4J_server_memory_heap_initial__size: "512m"
      NEO4J_server_memory_heap_max__size: "1G"
      NEO4J_server_memory_pagecache_size: "1G"
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
